# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
# import numpy package
import numpy as np

In [4]:
# the alias `np` is a convention for numpy
np

<module 'numpy' from 'C:\\Users\\dell\\anaconda3\\envs\\ml-zoomcamp\\Lib\\site-packages\\numpy\\__init__.py'>

## Creating arrays


In [5]:
# Array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# Array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
# Array of a particular size filled with a number
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [15]:
# Create an area from a list and store in a variable
a = np.array([1, 2, 3, 5, 7, 12])
a

array([ 1,  2,  3,  5,  7, 12])

In [17]:
# Change an element of an array
a[2] = 10

In [18]:
# Visualize the array
a

array([ 1,  2, 10,  5,  7, 12])

In [8]:
# Create an array from 3 (inclusive) to 10 (exclusive)
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
# Create an area from 0 to 100, with a size 11
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [25]:
# Two-dimensional array of 5 rows and 2 columns filled with zeros
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
# Two dimensional array of three rows and three columns
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [13]:
# Change the value at the first row and the second column
n[0, 1] = 20

In [16]:
# Visualize the result
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [17]:
# Rewrite the third row
n[2] = [1, 1, 1]

In [18]:
# Check the array
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [19]:
# Rewrite the third column
n[:, 2] = [0, 1, 2]

In [20]:
# Check the result
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays


In [21]:
# Random array of 5 rows and 2 columns
np.random.seed(2) # to make the result reproducible
100 * np.random.rand(5, 2) # from the standard uniform distribution

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [23]:
# Random array from the normal distribution
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [25]:
# Random array of integers
np.random.seed(2)
np.random.randint(low = 0, high = 100, size = (5, 2)) # low for the lowest number included, high for the highest excluded

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [26]:
# Create an array
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [27]:
# Performing element-wise operations on an array
b = (10 + (a * 2)) ** 2 / 100

In [28]:
# Result
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [29]:
# More operations
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [30]:
# an array
a

array([0, 1, 2, 3, 4])

In [31]:
# Compare element-wise with 2
a >= 2

array([False, False,  True,  True,  True])

In [32]:
# an array
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [33]:
# Comparing two arrays element-wise
a > b

array([False, False,  True,  True,  True])

In [35]:
# returns elements of a for which a > b is true
a[a > b]

array([2, 3, 4])

## Summarizing operations

In [36]:
# array
a

array([0, 1, 2, 3, 4])

In [37]:
# standard deviation
a.std()

1.4142135623730951

In [39]:
# smallest number
a.min()

0

In [41]:
# highest number
a.max()

4

In [42]:
# sum of numbers
a.sum()

10

### Next

Linear algebra refresher

---