# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [1]:
# import numpy package
import numpy as np

## Vector operations

In [2]:
# create a vector
u = np.array([2, 4, 5, 6])

In [4]:
# Element-wise operation with vectors
2 * u

array([ 4,  8, 10, 12])

In [5]:
# create a vector
v = np.array([1, 0, 0, 2])

In [6]:
# Element-wise addition between vectors
u + v

array([3, 4, 5, 8])

In [8]:
# Element-wise multiplication with vectors
u * v

array([ 2,  0,  0, 12])

## Multiplication

In [9]:
# length of vector
v.shape[0]

4

In [14]:
# Function for dot product
def vector_vector_multiplication(u, v):
    """
    Dot product of two vectors of same size.
    """
    # To make sure the two vectors have the same size
    assert (u.shape[0] == v.shape[0]), f"The two vectors have different shapes."

    # Initializing parameters for the loop 
    n = u.shape[0]
    result = 0.0

    # Loop for vector multiplication
    for i in range(n):
        result += u[i] * v[i]
    
    return result

In [16]:
# Call our dot product function
vector_vector_multiplication(u, v)

14.0

In [17]:
# When the two arrays don't hve the same size
a = np.array([1, 2, 3])
vector_vector_multiplication(u, a)

AssertionError: The two vectors have different shapes.

In [18]:
# The built-in dot product function
u.dot(v)

14

In [19]:
# Create a matrix 
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [20]:
# shape of the matrix
U.shape

(3, 4)

In [24]:
# Function for matrix - vector multiplication
def matrix_vector_multiplication(U, v):
    """
    Multiplies a matrix U with a vector v.
    """
    # The matrix should as many columns as the vectors has rows
    assert U.shape[1] == v.shape[0], f"The matrix number of columns is different from the vector number of rows."

    # Initializing parameters for the loop
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    # Looping to get the result 
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [25]:
# Call of matrix_vector_multiplication
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [26]:
# When the sizes dom't correspond
matrix_vector_multiplication(U, a)

AssertionError: The matrix number of columns is different from the vector number of rows.

In [27]:
# Built-in dot function can be used for matrix-vector multiplication
U.dot(v)

array([14,  5,  5])

In [28]:
# Create a matrix
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])

In [29]:
# Matrices multiplication
def matrix_matrix_multiplication(U, V):
    """Multiplies a matrix U with a matrix V"""
    assert U.shape[1] == V.shape[0], f"The matrix U number of columns should be equal to the matrix V number of rows."

    # Initializing parameters for the loop
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))

    # Looping to get the result
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [30]:
# Calling the matrices multiplication
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [35]:
# When dimensions don't match
A = np.array([[1, 2, 3], [4, 9, 0]])
matrix_matrix_multiplication(U, A)

AssertionError: The matrix U number of columns should be equal to the matrix V number of rows.

In [36]:
# The dot function can be used for matrices multiplication
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [39]:
# Create an identity matrix of size 3
I = np.eye(3)

In [40]:
# A vector V
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [41]:
# Multiplying a matrix by th identty matrix
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [42]:
# Create a square matrix from the 3 first rows of V
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [44]:
# The inverse of our square matrix
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [45]:
# A matrix multiplied with its inverse gives the identity
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Next 

Intro to Pandas

---