# Session 01 Homework

As the environment has already been set up, we can process to answer questions.

## Q1. Pandas version

In [1]:
# import pandas and get its version
import pandas as pd
pd.__version__

'2.2.2'

## Get the data
For this homework, we'll use the Laptops Price dataset. Download it from [here](https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv) or get it with:

In [2]:
# Read the data
df = pd.read_csv("https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv")

# Three first rows
df.head(3)

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   

        Model            CPU  RAM  Storage Storage type  GPU  Screen Touch  \
0  ExpertBook  Intel Core i5    8      512          SSD  NaN    15.6    No   
1          Go  Intel Celeron    8      256          SSD  NaN    15.6    No   
2  ExpertBook  Intel Core i3    8      256          SSD  NaN    15.6    No   

   Final Price  
0       1009.0  
1        299.0  
2        789.0

## Q2. Records count

In [3]:
# Number of records of the dataset
len(df)

2160

## Q3. Laptop brands

In [4]:
# Number of laptop brands
df.Brand.nunique()

27

## Q4. Missing values

In [5]:
# Number of columns with missing values
len(
    df.isnull().sum()[
    df.isnull().sum() != 0
    ]
)

3

## Q5. Maximum final price

In [6]:
# Maximum final price of Dell notebooks
df[df["Brand"] == "Dell"]["Final Price"].max()

3936.0

## Q6. Median value of Screen

1. Let's find the median value of `Screen` column in the dataset:

In [7]:
# median of screen sizes
df.Screen.median()

15.6

2. Next, we can calculate the most frequent value of the same Screen column:

In [8]:
# most frequent value
df.Screen.mode()

0    15.6
Name: Screen, dtype: float64

3. Let's use fillna method to fill the missing values in Screen column with the most frequent value from the previous step:

In [9]:
# fill missing values
df["Screen"] = df.Screen.fillna(df.Screen.mode().loc[0])

# Check if there is still missing values in `Screen` column
df.Screen.isnull().sum()

0

4. Now, we calculate the median value of Screen once again:

In [10]:
# new median of Screen size
df.Screen.median()

15.6

No, it has not change.

## Sum of weights

1. We select all the "Innjoo" laptops from the dataset:

In [11]:
# Dataset of Innjoo Laptops
df_Injoo = df[df.Brand == "Innjoo"]

# Visualize
df_Injoo

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

2. We select only columns `RAM`, `Storage`, `Screen`:

In [12]:
# Subset of data
df_Injoo_subset = df_Injoo[["RAM", "Storage", "Screen"]]

# result
df_Injoo_subset

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

3. We create `X`, the underlying NumPy array:

In [13]:
# import numpy package
import numpy as np

# Create array of data
X = np.array(df_Injoo_subset)
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

4. We compute matrix-matrix multiplication between the transpose of `X` and `X` and call it `XTX`:

In [14]:
# Compute matrix-matrix multiplication
XTX = X.T.dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

5. The inverse of `XTX`:

In [15]:
# Inverse of the matrix `XTX`
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

6. We now create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`:

In [16]:
# Create an array
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

7. Let's multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y` and call the resuly `w`:

In [17]:
# Multiply a matrix with an array
w = (XTX_inv.dot(X.T)).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

8. The sum of all the elements of the result is given by:

In [18]:
# Sum of all elements
w.sum()

91.29988062995815

---